### ISSUE TITLE
Get maximum console width and height for the device

### ISSUE THREAD

**Issue by damy90** [damy90/C-2-Team-Ogre-Mage-#2]
Reproducible with sufficiently high value for consoleWidth or consoleHeight.
Solution: detect max console window size

Exeption:
Unhandled Exception: System.ArgumentOutOfRangeException: The value must be less than the console's current maximum window size of 58 in that dimension
. Note that this value depends on screen resolution and the console font.
Parameter name: height
Actual value was 70.
   at System.Console.SetWindowSize(Int32 width, Int32 height)
   at MainGame.Main(String[] args) in c:\Users\dany\Dropbox\telerik\CSharp2\Teamwork 2\C-2-Team-Ogre-Mage-\Hell-Quiz\MainGame\MainGame.cs:line 31

row 31

**Comment by damy90** [comment]
Fixed
